#配置程序启动端口
server:
  port: 80

#配置数据源
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/demo/bookdemo/**/mapper/*.xml